## 선형대수학과 벡터

In [1]:
import numpy as np
x = np.array([3,4])
print("sqrt(dot(x,x))= ", np.sqrt(np.dot(x,x)))
print("sqrt(sum(x*x))= ", np.sqrt(np.sum(x*x)))
print("norm(x)= ", np.linalg.norm(x)) ## linalg = linier algebra

sqrt(dot(x,x))=  5.0
sqrt(sum(x*x))=  5.0
norm(x)=  5.0


In [2]:
v=np.array([3,4])
u=v/np.linalg.norm(v)
print(u)
print(np.linalg.norm(u))

[0.6 0.8]
1.0


In [3]:
x=([3,4,5,6])
u=x/np.linalg.norm(x)
print(u)

[0.32349832 0.43133109 0.53916387 0.64699664]


In [4]:
a=np.array([8,13])
b=np.array([26,7])
c=a+b
print(c)

[34 20]


In [5]:
d=np.array([4,5])
e=np.array([3,8])
f=d+e
print(f)

[ 7 13]


In [6]:
a=np.array([12,2])
b=np.array([4, 5])
c=a-b
print(c)

[ 8 -3]


In [7]:
d=np.array([1,2])
e=np.array([2,1])
f=d-e
print(f)

[-1  1]


In [8]:
## 벡터 내적의 활용 ( 위치 )

hero = np.array([0,1])
enemyA = np.array([4,3])
enemyB = np.array([4, -3])
hero_norm = np.linalg.norm(hero)
enemyA_norm=np.linalg.norm(enemyA)
enemyB_norm=np.linalg.norm(enemyB)
h_eA_cos = np.dot(hero, enemyA)/(hero_norm*enemyA_norm)
h_eB_cos = np.dot(hero, enemyB)/(hero_norm*enemyB_norm)
print(h_eA_cos)
print(h_eB_cos)
thetaA = np.arccos(h_eA_cos)
thetaB = np.arccos(h_eB_cos)
print(thetaA)
print(thetaB)

0.6
-0.6
0.9272952180016123
2.214297435588181


#### 외적

In [9]:
y = np.array([2,4])
x = np.array([4,3])
x_n=x/np.linalg.norm(x)
proj_result=np.dot(y, x_n)*x_n
print(proj_result)

[3.2 2.4]


In [10]:
from sklearn import svm
x = [[0,0], [1,1]]
y = [0,1]
clf = svm.SVC()
clf.fit(x,y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
clf.predict([[-1.,-2.]])

array([0])

In [12]:
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
np.set_printoptions(formatter={'float':'{:0.3f}'.format})
print("A= \n", A)
print("Inverse of A = \n", A_inv)
print("A*A_inv = \n", np.dot(A,A_inv))
print("A_inv*A = \n", np.dot(A_inv,A))

A= 
 [[1 2]
 [3 4]]
Inverse of A = 
 [[-2.000 1.000]
 [1.500 -0.500]]
A*A_inv = 
 [[1.000 0.000]
 [0.000 1.000]]
A_inv*A = 
 [[1.000 0.000]
 [0.000 1.000]]


In [13]:
A=np.array([[1,2,3],[6,5,4],[9,8,7]])
W, V=np.linalg.eig(A)
print(W)
print(V)
W, V=np.linalg.eig(np.transpose(A))
print(W)
print(V)
B=np.array([[1,0,0],[0,2,0],[0,0,3]])
W, V = np.linalg.eig(B)
print(W)
print(V)
W, V = np.linalg.eig(np.linalg.inv(B))
print(W)
print(V)

[14.639 -1.639 -0.000]
[[0.255 0.789 0.408]
 [0.502 -0.493 -0.816]
 [0.826 -0.366 0.408]]
[14.639 -1.639 0.000]
[[0.611 0.880 -0.239]
 [0.577 0.233 -0.796]
 [0.542 -0.414 0.557]]
[1.000 2.000 3.000]
[[1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]]
[1.000 0.500 0.333]
[[1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]]


### 공분산 과 상관계수(correlation)

In [16]:
x_1=np.array([3,4,5,4,3,4,5])
x_2=np.array([1,2,3,4,5,6,7])
x_3=np.array([4,4,4,4,4,4,4])

In [17]:
x1_diff=x_1 - x_1.mean()
x2_diff=x_2 - x_2.mean()
x12_cov = np.dot(x1_diff, x2_diff)/7
print("covariance of x_1 and x_2 is : ", x12_cov)
print("correlation coefficient of x_1 and x_2 is : ", x12_cov/(x_1.std()*x_2.std()))

covariance of x_1 and x_2 is :  0.5714285714285714
correlation coefficient of x_1 and x_2 is :  0.37796447300922725


In [18]:
x=np.arange(5)
y=np.arange(4, -1, -1)
x_diff = x-x.mean()
y_diff = y-y.mean()
xy_cov = np.dot(x_diff, y_diff)/5 ## 공분산
xy_cov_metrix = np.cov(x,y, ddof=0)
xy_cor = np.corrcoef(x,y) ## 상관계수

print("covariance of x and y : ", xy_cov)
print("covariance matrix of x and y : \n", xy_cov_metrix)
print("correlation coefficient of x and y : \n", xy_cor)

covariance of x and y :  -2.0
covariance matrix of x and y : 
 [[2.000 -2.000]
 [-2.000 2.000]]
correlation coefficient of x and y : 
 [[1.000 -1.000]
 [-1.000 1.000]]


#### 예제

In [19]:
x_1 = np.array([35, 5, 0, 20, 15])
x_2 = np.array([11, 12, 5, 9, 8])
x_3 = np.array([0.5, 0, 10, 4.5, 5])

x_1_mean = x_1.mean()
x_2_mean = x_2.mean()
x_3_mean = x_3.mean()

print(x_1_mean, x_2_mean, x_3_mean)

x_1_var=x_1.var()
x_2_var=x_2.var()
x_3_var=x_3.var()

print(x_1_var, x_2_var, x_3_var)

x_total = np.array([x_1, x_2, x_3])
print(x_total)
print('Covariance matrix : \n', np.cov(x_total, ddof=0))

X_cc = np.corrcoef(x_total)
print('Correlation Coefficients :\n', X_cc)
print(f'rho(x1, x2) : {X_cc[1][0]:3.2}')
print(f'rho(x2, x3) : {X_cc[1][2]:3.2}')
print(f'rho(x3, x1) : {X_cc[2][0]:3.2}')

15.0 9.0 4.0
150.0 6.0 13.1
[[35.000 5.000 0.000 20.000 15.000]
 [11.000 12.000 5.000 9.000 8.000]
 [0.500 0.000 10.000 4.500 5.000]]
Covariance matrix : 
 [[150.000 14.000 -23.500]
 [14.000 6.000 -8.800]
 [-23.500 -8.800 13.100]]
Correlation Coefficients :
 [[1.000 0.467 -0.530]
 [0.467 1.000 -0.993]
 [-0.530 -0.993 1.000]]
rho(x1, x2) : 0.47
rho(x2, x3) : -0.99
rho(x3, x1) : -0.53


### 왜도 와 첨도

In [21]:
import scipy.stats as ss

x1 = ss.skew([1,2,3,4,5,5,5,5])
x2 = ss.skew([1,2,3,4,5,1,1,1])
y1 = ss.kurtosis([1,2,2,2,3,3,3,3,3,4,4,4,5])
y2 = ss.kurtosis([1,2,3,4,5])
y3 = ss.kurtosis([1,2,3,4,4,4,4,4,3,2,1])
print(x1)
print(x2)
print(y1)
print(y2)
print(y3)

-0.7244179326244428
0.7244179326244428
-0.4795918367346941
-1.3
-1.2672516359309935
